#!/bin/bash


_repolink () {
    local regex
    regex='(https?)://github.com/.+/.+'
    if [[ $UPSTREAM_REPO_URL == "Man-Userbot" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL21yaXNtYW5heml6L01hbi1Vc2VyYm90L2FyY2hpdmUvTWFuLVVzZXJib3Quemlw" | base64 -d
    elif [[ $UPSTREAM_REPO_URL == "man-userbot" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL21yaXNtYW5heml6L01hbi1Vc2VyYm90L2FyY2hpdmUvTWFuLVVzZXJib3Quemlw" | base64 -d
    elif [[ $UPSTREAM_REPO_URL =~ $regex ]]
    then
        if [[ $UPSTREAM_REPO_URL_BRANCH ]]
        then
            echo "${UPSTREAM_REPO_URL}/archive/${UPSTREAM_REPO_BRANCH}.zip"
        else
            echo "${UPSTREAM_REPO_URL}/archive/Man-Userbot.zip"
        fi
    else
        echo "aHR0cHM6Ly9naXRodWIuY29tL21yaXNtYW5heml6L01hbi1Vc2VyYm90L2FyY2hpdmUvTWFuLVVzZXJib3Quemlw" | base64 -d
    fi
}


start_bot () {
    local zippath
    zippath="manuserbot.zip"
    echo "  Downloading source code ..."
    wget -q $(_repolink) -O "$zippath"
    echo "  Unpacking Data ..."
    PATHMAN=$(zipinfo -1 "$zippath" | grep -v "/.");
    unzip -qq "$zippath"
    echo "  Processing Codes..."
    rm -rf "$zippath"
    sleep 5
    cd $PATHMAN
    echo "  • Starting Man-UserBot •  "
    echo "
                    ███╗   ███╗ █████╗ ███╗   ██╗
                    ████╗ ████║██╔══██╗████╗  ██║
                    ██╔████╔██║███████║██╔██╗ ██║
                    ██║╚██╔╝██║██╔══██║██║╚██╗██║
                    ██║ ╚═╝ ██║██║  ██║██║ ╚████║
    "
    echo "
        ██╗   ██╗███████╗███████╗██████╗ ██████╗  ██████╗ ████████╗
        ██║   ██║██╔════╝██╔════╝██╔══██╗██╔══██╗██╔═══██╗╚══██╔══╝
        ██║   ██║███████╗█████╗  ██████╔╝██████╔╝██║   ██║   ██║   
        ██║   ██║╚════██║██╔══╝  ██╔══██╗██╔══██╗██║   ██║   ██║   
        ╚██████╔╝███████║███████╗██║  ██║██████╔╝╚██████╔╝   ██║   
         ╚═════╝ ╚══════╝╚══════╝╚═╝  ╚═╝╚═════╝  ╚═════╝    ╚═╝   
    "

    python3 ../setup/updater.py ../requirements.txt requirements.txt
    python3 -m userbot
}

start_bot